// Package k6run shells out to the k6 binary to execute a load test
// scenario, passing it the generated state dictionary via an environment
// variable, and parses the resulting --summary-export JSON so the report
// phase can show pass/fail thresholds and key metrics.
package k6run

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/thecoons/myrtille/internal/config"
	"github.com/thecoons/myrtille/internal/dashboardconfig"
)

// k6ThresholdsFailedExitCode is k6's documented exit code when the script
// ran to completion but one or more thresholds failed.
const k6ThresholdsFailedExitCode = 99

// MetricSummary holds the stats k6 reports for a single metric (shape
// varies by metric type: Trend metrics have avg/min/max/percentiles,
// Counter/Rate metrics have count/rate, Gauge metrics have value), plus any
// threshold results attached to that metric.
type MetricSummary struct {
	Values     map[string]float64
	Thresholds map[string]bool
}

// CheckResult holds one named check's pass/fail counts, as reported under
// root_group (and its nested groups) in k6's --summary-export JSON. Path is
// k6's own dotted/double-colon path (e.g. "::my group::my check"), unique
// across the whole run even when two groups reuse a check name.
type CheckResult struct {
	Name   string
	Path   string
	Passes int
	Fails  int
}

// Summary is a loosely-typed view of k6's --summary-export JSON: k6's exact
// schema varies across versions and metric types, so rather than modeling
// it exhaustively we keep each metric's numeric fields and threshold results.
type Summary struct {
	Metrics map[string]MetricSummary
	// Checks is every named check, flattened out of root_group's (possibly
	// nested) groups, sorted by Path for stable report output.
	Checks []CheckResult
}

// Result reports how a k6 run went.
type Result struct {
	ExitCode         int
	Passed           bool // exit code 0
	ThresholdsFailed bool // exit code 99, per k6 convention
	Duration         time.Duration
	Summary          *Summary // nil if the summary file could not be read/parsed
}

// Run executes `k6 run <scriptPath> <args...>` with the state dict file path
// exposed as the env var named by cfg.K6.StateEnv, streaming the
// subprocess's stdout/stderr to stdout/stderr as it runs. scriptPath is
// either cfg.K6ScriptPath() (a hand-written script) or a path generated by
// internal/k6gen from cfg.K6.Steps — the caller resolves which. A non-zero
// k6 exit code (including a thresholds failure) is reported in Result
// rather than returned as an error, since the load test itself still ran to
// completion and should still produce a report.
func Run(ctx context.Context, cfg *config.Config, scriptPath, stateFilePath string, stdout, stderr io.Writer) (*Result, error) {
	k6Bin, liveDashboard, err := resolveK6Binary()
	if err != nil {
		return nil, err
	}

	// A quick note when the co-located k6 kicked in with no explicit
	// $MYRTILLE_K6_BIN — the one case where the live dashboard turns on
	// without anything the user configured, so it's worth being clear about
	// which binary is actually running. Silent otherwise: an explicit
	// MYRTILLE_K6_BIN speaks for itself, and no live dashboard is exactly
	// today's default (unchanged), nothing new to announce.
	if v, ok := os.LookupEnv(k6BinEnv); liveDashboard && (!ok || v == "") {
		fmt.Fprintf(stderr, "k6 binary: %s (bundled next to myrtille)\n", k6Bin)
	}

	summaryPath := summaryFilePath()
	defer os.Remove(summaryPath)

	args := []string{"run", scriptPath, "--summary-export", summaryPath}

	// liveDashboard (only true for the custom binary, which alone bundles
	// k6/x/promscrape) serves k6's web-dashboard on a real port — see
	// docs/plans/xk6-live-dashboard.md, step 4. period is forced low: k6's
	// 10s default would otherwise produce very few snapshots for a short
	// run (e.g. this project's own demo scenario), and k6 already caps
	// total points at 2880 regardless, so a small floor is safe for long
	// runs too. No `open=`: k6 already prints "web dashboard: http://..."
	// to stdout on its own (Run streams k6's stdout straight through), so
	// there's nothing extra for myrtille to print, and no browser pops up
	// uninvited in a CI/headless run. port=0 (not a fixed port) so
	// parallel runs on the same machine don't collide. Without the custom
	// binary, no --out web-dashboard is requested at all — there's nobody
	// to serve it to (no live dashboard) and nothing left that consumes a
	// headless record file (that was the now-removed homemade HTML
	// report's job).
	if liveDashboard {
		args = append(args, "--out", "web-dashboard=period=1s&port=0")
	}

	args = append(args, cfg.K6.Args...)

	envOverrides := map[string]string{cfg.K6.StateEnv: stateFilePath}

	// Only meaningful alongside the live dashboard: XK6_DASHBOARD_CONFIG
	// replaces k6's default dashboard config wholesale (see
	// dashboardconfig's package doc), so there's no point generating it for
	// the headless port=-1 case nobody's going to look at. Errors here fail
	// the run outright rather than falling back to the plain default
	// config — see Build's doc comment for why.
	if liveDashboard && cfg.Service.Metrics.URL != "" {
		configJSON, err := dashboardconfig.Build(ctx, cfg.Service.Metrics.URL)
		if err != nil {
			return nil, fmt.Errorf("building dashboard config: %w", err)
		}

		configPath := dashboardConfigPath()
		defer os.Remove(configPath)
		if err := os.WriteFile(configPath, configJSON, 0o644); err != nil {
			return nil, fmt.Errorf("writing dashboard config: %w", err)
		}

		envOverrides["XK6_DASHBOARD_CONFIG"] = configPath
	}

	cmd := exec.CommandContext(ctx, k6Bin, args...)
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	cmd.Env = buildEnv(envOverrides)

	start := time.Now()
	runErr := cmd.Run()
	duration := time.Since(start)

	exitCode := 0
	if runErr != nil {
		var exitErr *exec.ExitError
		if errors.As(runErr, &exitErr) {
			exitCode = exitErr.ExitCode()
		} else {
			return nil, fmt.Errorf("running k6: %w", runErr)
		}
	}

	result := &Result{
		ExitCode:         exitCode,
		Passed:           exitCode == 0,
		ThresholdsFailed: exitCode == k6ThresholdsFailedExitCode,
		Duration:         duration,
	}

	if data, readErr := os.ReadFile(summaryPath); readErr == nil {
		if summary, parseErr := parseSummary(data); parseErr == nil {
			result.Summary = summary
		}
	}

	return result, nil
}

// k6BinEnv, when set, overrides which k6 binary Run shells out to — the
// path to a custom binary built by scripts/build-k6.sh (bundling
// k6/x/promscrape, see docs/plans/xk6-live-dashboard.md), instead of
// whatever "k6" resolves to on PATH. Unset by default so existing installs
// (stock k6 on PATH) keep working unchanged; this becomes the default once
// the live-dashboard integration actually needs the extension at runtime.
const k6BinEnv = "MYRTILLE_K6_BIN"

// HasCustomBinary reports whether MYRTILLE_K6_BIN is set — i.e. whether a
// custom k6 binary bundling k6/x/promscrape will be used. internal/k6gen
// calls this before deciding whether to wire promscrape into a generated
// script: stock k6 doesn't have that extension, so injecting the import
// based on service.metrics.url alone (regardless of which binary will
// actually run the script) breaks any run that hasn't opted into
// MYRTILLE_K6_BIN — found by running examples/demo-service's own config
// (which sets service.metrics.url for the still-separate Go-side scraper)
// against stock k6: it failed trying to resolve k6/x/promscrape. Doesn't
// validate the path (unlike resolveK6Binary) — that's Run's job when it
// actually shells out; this only needs to answer "is the intent there".
func HasCustomBinary() bool {
	v, ok := os.LookupEnv(k6BinEnv)
	return ok && v != ""
}

// resolveK6Binary returns the path to the k6 executable Run should invoke:
// $MYRTILLE_K6_BIN if set (validated to exist), otherwise "k6" resolved
// from PATH as before — checked in that order. A release tarball extracts
// myrtille and its bundled k6 side by side (see
// docs/plans/single-binary-distribution.md), so the middle branch is what
// makes the live dashboard work out of the box for anyone using an official
// release, with no configuration at all. custom reports whether either of
// the first two branches matched — Run uses it to decide whether a live
// web-dashboard can be requested at all (only a binary bundling
// k6/x/promscrape supports it).
func resolveK6Binary() (path string, custom bool, err error) {
	if v, ok := os.LookupEnv(k6BinEnv); ok && v != "" {
		if _, err := os.Stat(v); err != nil {
			return "", false, fmt.Errorf("%s=%s: %w", k6BinEnv, v, err)
		}
		return v, true, nil
	}

	if v, ok := coLocatedK6Binary(); ok {
		return v, true, nil
	}

	path, err = exec.LookPath("k6")
	if err != nil {
		return "", false, fmt.Errorf("k6 binary not found on PATH: %w", err)
	}
	return path, false, nil
}

// coLocatedK6Binary looks for a "k6" file next to the currently running
// myrtille executable. Unlike MYRTILLE_K6_BIN (an explicit ask, so a
// mistake there should fail loudly), this is an implicit convenience: any
// failure along the way just means "no match, fall through to PATH" —
// never an error.
func coLocatedK6Binary() (string, bool) {
	self, err := os.Executable()
	if err != nil {
		return "", false
	}
	return coLocatedK6BinaryFor(self)
}

// coLocatedK6BinaryFor is coLocatedK6Binary's logic with the "self" path
// injected, so it's testable without depending on the test binary's own
// os.Executable() location.
func coLocatedK6BinaryFor(self string) (string, bool) {
	// os.Executable's result may itself be a symlink (e.g. myrtille
	// installed at /usr/local/bin/myrtille pointing elsewhere) — resolve it
	// so the directory searched is where the real binary (and whatever's
	// bundled alongside it) actually lives, not the symlink's own directory.
	resolved, err := filepath.EvalSymlinks(self)
	if err != nil {
		return "", false
	}

	candidate := filepath.Join(filepath.Dir(resolved), "k6")
	info, err := os.Stat(candidate)
	if err != nil || info.IsDir() {
		return "", false
	}

	return candidate, true
}

func summaryFilePath() string {
	return fmt.Sprintf("%s/myrtille-k6-summary-%d.json", os.TempDir(), time.Now().UnixNano())
}

func dashboardConfigPath() string {
	return fmt.Sprintf("%s/myrtille-k6-dashboard-config-%d.json", os.TempDir(), time.Now().UnixNano())
}

// buildEnv returns the child process environment: the current process's
// environment with custom entries applied on top, deduplicating by key
// (repeating a key in a Cmd.Env slice has unspecified precedence, so we
// resolve it ourselves).
func buildEnv(custom map[string]string) []string {
	env := make(map[string]string)
	for _, kv := range os.Environ() {
		if i := strings.IndexByte(kv, '='); i >= 0 {
			env[kv[:i]] = kv[i+1:]
		}
	}
	for k, v := range custom {
		env[k] = v
	}

	out := make([]string, 0, len(env))
	for k, v := range env {
		out = append(out, k+"="+v)
	}
	return out
}

// rawCheck/rawGroup mirror the shape of a group under root_group in k6's
// --summary-export JSON: each group has its own checks (keyed by check name)
// plus nested sub-groups, recursively, so a scenario using group() reports
// checks at whatever depth they were declared at.
type rawCheck struct {
	Name   string `json:"name"`
	Path   string `json:"path"`
	Passes int    `json:"passes"`
	Fails  int    `json:"fails"`
}

type rawGroup struct {
	Checks map[string]rawCheck `json:"checks"`
	Groups map[string]rawGroup `json:"groups"`
}

// flattenChecks walks a group's checks and its nested groups' checks into a
// single slice, in no particular order (the caller sorts by Path).
func flattenChecks(g rawGroup) []CheckResult {
	checks := make([]CheckResult, 0, len(g.Checks))
	for _, c := range g.Checks {
		checks = append(checks, CheckResult{Name: c.Name, Path: c.Path, Passes: c.Passes, Fails: c.Fails})
	}
	for _, sub := range g.Groups {
		checks = append(checks, flattenChecks(sub)...)
	}
	return checks
}

// parseSummary decodes a k6 --summary-export JSON payload. Each metric's
// fields are split between numeric stats (kept in Values) and its
// "thresholds" object (kept in Thresholds), tolerating unknown/extra
// fields since k6's summary schema isn't stable across versions. Named
// checks are read from root_group, which k6 always populates regardless of
// whether the script defines its own handleSummary().
func parseSummary(data []byte) (*Summary, error) {
	var raw struct {
		Metrics   map[string]map[string]any `json:"metrics"`
		RootGroup rawGroup                  `json:"root_group"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("parsing k6 summary: %w", err)
	}

	summary := &Summary{Metrics: make(map[string]MetricSummary, len(raw.Metrics))}
	for name, fields := range raw.Metrics {
		ms := MetricSummary{Values: map[string]float64{}, Thresholds: map[string]bool{}}
		for key, val := range fields {
			if key == "thresholds" {
				thresholds, ok := val.(map[string]any)
				if !ok {
					continue
				}
				for expr, tv := range thresholds {
					tobj, ok := tv.(map[string]any)
					if !ok {
						continue
					}
					if ok2, ok := tobj["ok"].(bool); ok {
						ms.Thresholds[expr] = ok2
					}
				}
				continue
			}
			if fv, ok := val.(float64); ok {
				ms.Values[key] = fv
			}
		}
		summary.Metrics[name] = ms
	}

	summary.Checks = flattenChecks(raw.RootGroup)
	sort.Slice(summary.Checks, func(i, j int) bool { return summary.Checks[i].Path < summary.Checks[j].Path })

	return summary, nil
}
