// Package k6run shells out to the k6 binary to execute a load test
// scenario, passing it the generated state dictionary via an environment
// variable, and parses the resulting --summary-export JSON so the report
// phase can show pass/fail thresholds and key metrics.
package k6run

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"
	"syscall"
	"time"

	"github.com/thecoons/myrtille/internal/config"
	"github.com/thecoons/myrtille/internal/dashboardconfig"
)

// k6ThresholdsFailedExitCode is k6's documented exit code when the script
// ran to completion but one or more thresholds failed.
const k6ThresholdsFailedExitCode = 99

// dashboardHTMLFormat is the report.formats value that requests
// xk6-dashboard's own standalone HTML export (--out
// web-dashboard=...&export=...) alongside the live dashboard — see
// docs/plans/xk6-dashboard-html-export.md. Only meaningful with the custom
// binary, same as the live dashboard itself.
const dashboardHTMLFormat = "dashboard-html"

// MetricSummary holds the stats k6 reports for a single metric (shape
// varies by metric type: Trend metrics have avg/min/max/percentiles,
// Counter/Rate metrics have count/rate, Gauge metrics have value), plus any
// threshold results attached to that metric.
type MetricSummary struct {
	Values     map[string]float64
	Thresholds map[string]bool
}

// CheckResult holds one named check's pass/fail counts, as reported under
// root_group (and its nested groups) in k6's --summary-export JSON. Path is
// k6's own dotted/double-colon path (e.g. "::my group::my check"), unique
// across the whole run even when two groups reuse a check name.
type CheckResult struct {
	Name   string
	Path   string
	Passes int
	Fails  int
}

// Summary is a loosely-typed view of k6's --summary-export JSON: k6's exact
// schema varies across versions and metric types, so rather than modeling
// it exhaustively we keep each metric's numeric fields and threshold results.
type Summary struct {
	Metrics map[string]MetricSummary
	// Checks is every named check, flattened out of root_group's (possibly
	// nested) groups, sorted by Path for stable report output.
	Checks []CheckResult
}

// Result reports how a k6 run went.
type Result struct {
	ExitCode         int
	Passed           bool // exit code 0
	ThresholdsFailed bool // exit code 99, per k6 convention
	Duration         time.Duration
	Summary          *Summary // nil if the summary file could not be read/parsed
	// DashboardHTMLPath, when non-empty, points at xk6-dashboard's own
	// standalone HTML export (see dashboardHTMLFormat) written to a
	// temporary location — set only when "dashboard-html" was in
	// cfg.Report.Formats and the file was actually produced. The caller
	// (the report package) is responsible for moving/copying it into the
	// final report directory and cleaning it up; Run itself doesn't delete
	// it, unlike the summary/dashboard-config temp files it fully consumes
	// internally.
	DashboardHTMLPath string
}

// Run executes `k6 run <scriptPath> <args...>` with the state dict file path
// exposed as the env var named by cfg.K6.StateEnv, streaming the
// subprocess's stdout/stderr to stdout/stderr as it runs. scriptPath is
// either cfg.K6ScriptPath() (a hand-written script) or a path generated by
// internal/k6gen from cfg.K6.Steps — the caller resolves which. A non-zero
// k6 exit code (including a thresholds failure) is reported in Result
// rather than returned as an error, since the load test itself still ran to
// completion and should still produce a report.
func Run(ctx context.Context, cfg *config.Config, scriptPath, stateFilePath string, stdout, stderr io.Writer) (*Result, error) {
	k6Bin, liveDashboard, err := resolveK6Binary()
	if err != nil {
		return nil, err
	}

	wantsDashboardHTML := slices.Contains(cfg.Report.Formats, dashboardHTMLFormat)
	if wantsDashboardHTML && !liveDashboard {
		return nil, fmt.Errorf("report.formats: %q requires the custom k6 binary (MYRTILLE_K6_BIN or a co-located k6) — see the README's \"Live dashboard\" section", dashboardHTMLFormat)
	}

	// A quick note when the co-located k6 kicked in with no explicit
	// $MYRTILLE_K6_BIN — the one case where the live dashboard turns on
	// without anything the user configured, so it's worth being clear about
	// which binary is actually running. Silent otherwise: an explicit
	// MYRTILLE_K6_BIN speaks for itself, and no live dashboard is exactly
	// today's default (unchanged), nothing new to announce.
	if v, ok := os.LookupEnv(k6BinEnv); liveDashboard && (!ok || v == "") {
		fmt.Fprintf(stderr, "k6 binary: %s (bundled next to myrtille)\n", k6Bin)
	}

	summaryPath := summaryFilePath()
	defer os.Remove(summaryPath)

	args := []string{"run", scriptPath, "--summary-export", summaryPath}

	// Quiet by default: kills k6's own ASCII banner and per-second progress
	// lines, which get repeated once per scenario in suite mode and drown
	// out myrtille's own "=== scenario: ... ===" framing — the final
	// summary block (checks/CUSTOM/HTTP/...) isn't gated by --quiet, so
	// nothing useful is lost. Skipped when the live dashboard is active:
	// --quiet also suppresses the one line k6 prints with the dashboard's
	// URL (port=0 means it's only known once k6 binds it, so myrtille can't
	// print it instead), which would defeat the point of that mode.
	// cfg.K6.Args, appended below, can still override either way — k6's
	// flag parser applies the last occurrence of a flag, so e.g.
	// "--quiet=false" there wins over this default.
	if !liveDashboard {
		args = append(args, "--quiet")
	}

	// liveDashboard (only true for the custom binary, which alone bundles
	// k6/x/promscrape) serves k6's web-dashboard on a real port — see
	// docs/plans/xk6-live-dashboard.md, step 4. period is forced low: k6's
	// 10s default would otherwise produce very few snapshots for a short
	// run (e.g. this project's own demo scenario), and k6 already caps
	// total points at 2880 regardless, so a small floor is safe for long
	// runs too. No `open=`: k6 already prints "web dashboard: http://..."
	// to stdout on its own (Run streams k6's stdout straight through), so
	// there's nothing extra for myrtille to print, and no browser pops up
	// uninvited in a CI/headless run. port=0 (not a fixed port) so
	// parallel runs on the same machine don't collide. Without the custom
	// binary, no --out web-dashboard is requested at all — there's nobody
	// to serve it to (no live dashboard) and nothing left that consumes a
	// headless record file (that was the now-removed homemade HTML
	// report's job).
	var dashboardHTMLPath string
	if liveDashboard {
		webDashboardOut := "web-dashboard=period=1s&port=0"
		if wantsDashboardHTML {
			dashboardHTMLPath = dashboardExportPath()
			webDashboardOut += "&export=" + dashboardHTMLPath
		}
		args = append(args, "--out", webDashboardOut)
	}

	args = append(args, cfg.K6.Args...)

	envOverrides := map[string]string{cfg.K6.StateEnv: stateFilePath}

	// Only meaningful alongside the live dashboard: XK6_DASHBOARD_CONFIG
	// replaces k6's default dashboard config wholesale (see
	// dashboardconfig's package doc), so there's no point generating it for
	// the headless port=-1 case nobody's going to look at. Errors here fail
	// the run outright rather than falling back to the plain default
	// config — see Build's doc comment for why.
	if liveDashboard && cfg.Service.Metrics.URL != "" {
		configJSON, err := dashboardconfig.Build(ctx, cfg.Service.Metrics.URL)
		if err != nil {
			return nil, fmt.Errorf("building dashboard config: %w", err)
		}

		configPath := dashboardConfigPath()
		defer os.Remove(configPath)
		if err := os.WriteFile(configPath, configJSON, 0o644); err != nil {
			return nil, fmt.Errorf("writing dashboard config: %w", err)
		}

		envOverrides["XK6_DASHBOARD_CONFIG"] = configPath
	}

	cmd := exec.CommandContext(ctx, k6Bin, args...)
	cmd.Stderr = stderr
	cmd.Env = buildEnv(envOverrides)

	// Only the live-dashboard path needs to watch stdout for the
	// "web dashboard: http://..." line — see stopEventWatchdog's doc
	// comment for why. Without it, stdout passes straight through exactly
	// as before this existed.
	var dashboardURLCh chan string
	if liveDashboard {
		dashboardURLCh = make(chan string, 1)
		cmd.Stdout = &dashboardURLScanner{Writer: stdout, urlCh: dashboardURLCh}
		// Its own process group so stopEventWatchdog can kill k6 *and*
		// anything it may have spawned (mirrors internal/servicelifecycle's
		// Handle.Stop — a plain cmd.Process.Kill() only reaches the direct
		// child; anything that child forked keeps running, still holding
		// the stdout pipe open, which hangs cmd.Wait() right where the
		// watchdog was trying to unblock it — found via a real repro with
		// a shell-script test double, not by inspection).
		cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	} else {
		cmd.Stdout = stdout
	}

	start := time.Now()
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("starting k6: %w", err)
	}

	exited := make(chan struct{})
	var runErr error
	go func() {
		runErr = cmd.Wait()
		close(exited)
	}()

	// Buffered so stopEventWatchdog's send (before it kills — see there)
	// never blocks on this being read.
	killed := make(chan struct{}, 1)
	if liveDashboard {
		go stopEventWatchdog(cmd, dashboardURLCh, exited, killed)
	}

	<-exited
	duration := time.Since(start)

	// Only safe to write to stderr again now: cmd.Wait() returning means
	// exec's own internal goroutine copying the process's stderr into this
	// same io.Writer has already finished (see os/exec's Cmd.Wait doc
	// comment) — printing this earlier, from stopEventWatchdog itself,
	// raced with that goroutine over the same underlying bytes.Buffer and
	// silently lost the message under -race (found by actually running
	// the reproduction test, not by inspection).
	select {
	case <-killed:
		fmt.Fprintf(stderr, "k6 did not exit within %s of the live dashboard reporting the run finished "+
			"(a known xk6-dashboard issue when a browser tab is left open on it) — killed it\n", dashboardStopGrace)
	default:
	}

	exitCode := 0
	if runErr != nil {
		var exitErr *exec.ExitError
		if errors.As(runErr, &exitErr) {
			exitCode = exitErr.ExitCode()
		} else {
			return nil, fmt.Errorf("running k6: %w", runErr)
		}
	}

	result := &Result{
		ExitCode:         exitCode,
		Passed:           exitCode == 0,
		ThresholdsFailed: exitCode == k6ThresholdsFailedExitCode,
		Duration:         duration,
	}

	if data, readErr := os.ReadFile(summaryPath); readErr == nil {
		if summary, parseErr := parseSummary(data); parseErr == nil {
			result.Summary = summary
		}
	}

	if wantsDashboardHTML {
		if info, statErr := os.Stat(dashboardHTMLPath); statErr == nil && info.Size() > 0 {
			result.DashboardHTMLPath = dashboardHTMLPath
		}
	}

	return result, nil
}

// dashboardURLPattern matches k6's own "web dashboard: http://..." line
// (see k6's internal/cmd/ui.go printExecutionDescription), only printed
// when the live dashboard is active and never gated behind --quiet in
// that case (see runner.go's own --quiet handling) — so it's always
// present exactly when stopEventWatchdog needs it.
var dashboardURLPattern = regexp.MustCompile(`web dashboard:\s*(\S+)`)

// dashboardURLScanner wraps k6's stdout, watching for the one line above
// to learn the live dashboard's actual URL (port=0 means the real port
// isn't known ahead of time) — every byte is still forwarded to Writer
// completely unmodified and without delay; this only ever adds a
// best-effort side channel, never changes what the terminal sees. Sends
// at most once, then stops scanning (urlCh is closed right after).
type dashboardURLScanner struct {
	io.Writer
	pending []byte
	urlCh   chan<- string
	found   bool
}

func (s *dashboardURLScanner) Write(p []byte) (int, error) {
	if !s.found {
		s.pending = append(s.pending, p...)
		if m := dashboardURLPattern.FindSubmatch(s.pending); m != nil {
			s.found = true
			s.urlCh <- string(m[1])
			close(s.urlCh)
			s.pending = nil
		} else if len(s.pending) > 4096 {
			// The marker line never showed up in the first 4KB of output
			// (unexpected — an older/newer k6 changed the wording?) — stop
			// accumulating unboundedly rather than buffer the whole run's
			// stdout for nothing.
			s.pending = s.pending[len(s.pending)-4096:]
		}
	}
	return s.Writer.Write(p)
}

// dashboardStopGrace bounds how long stopEventWatchdog waits for k6 to
// exit on its own after observing the live dashboard's "stop" SSE event,
// before force-killing it — long enough that other, real browser tabs
// (which received that same event and are expected to disconnect
// promptly on it) have a real chance to let k6 shut down cleanly by
// itself; short enough that the bug below can't hang a run indefinitely.
// A var, not a const, so tests can shorten it rather than actually wait
// out the real default.
var dashboardStopGrace = 5 * time.Second

// stopEventWatchdog works around a k6/xk6-dashboard bug (confirmed by
// reading k6 v2.2.0's own source, internal/dashboard/sse.go): shutting
// down the live dashboard's web server first waits for every open SSE
// /events connection — i.e. every browser tab with the dashboard still
// open — to disconnect on its own, with no timeout of its own. A tab left
// open past the end of a run (the ordinary case: nobody watches a
// dashboard through to the exact millisecond a test finishes) hangs the
// k6 process forever, which hangs Run behind it, which means the report
// step is never reached at all.
//
// Mitigation: connect to the dashboard's own /events stream ourselves —
// exactly the same endpoint a browser tab uses, no special access — and
// watch for the "stop" event k6 sends the instant it starts shutting
// down, confirmed (by reading that same source) to be sent *before* the
// blocking wait described above. Seeing it means the test itself is
// genuinely finished, not just idle; from there dashboardStopGrace gives
// the process a real chance to exit on its own before this steps in.
//
// A run without the bug (every dashboard tab already closed, or none ever
// opened) is unaffected either way: k6 exits on its own, closing exited,
// which this always checks for first.
//
// killed (buffered, capacity 1) is signaled right before the kill, never
// by writing to stderr directly from here — this runs concurrently with
// cmd itself, and cmd.Stderr writes into the very same stderr the caller
// passed in from its own internal I/O goroutine; writing to it from here
// too raced with that goroutine over the same underlying io.Writer (e.g. a
// non-thread-safe bytes.Buffer), silently losing the message under -race.
// The caller prints the explanation itself once cmd.Wait() has returned,
// when it's the only writer left.
func stopEventWatchdog(cmd *exec.Cmd, urlCh <-chan string, exited <-chan struct{}, killed chan<- struct{}) {
	var dashboardURL string
	select {
	case dashboardURL = <-urlCh:
	case <-exited:
		return
	}

	if !waitForDashboardStopEvent(dashboardURL, exited) {
		return
	}

	select {
	case <-exited:
		return
	case <-time.After(dashboardStopGrace):
	}

	// Sent before killing, not after: the caller only reads this once
	// exited has closed, which can't happen until the kill below actually
	// takes effect — sending first guarantees the buffered value is
	// already sitting there by the time it's read, with no reliance on
	// scheduling order between this goroutine and the caller's.
	killed <- struct{}{}
	// The whole process group (see the Setpgid comment where cmd is
	// built), not just cmd.Process — anything k6 itself spawned would
	// otherwise keep running and keep stdout's pipe open, hanging
	// cmd.Wait() right where this was trying to unblock it.
	_ = syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
}

// waitForDashboardStopEvent connects to dashboardURL+"/events" (the live
// dashboard's own SSE stream) and reports whether a "stop" event arrived
// before exited closed. Any failure along the way — a bad URL, a refused
// connection, the stream closing without ever sending "stop" — is treated
// as "nothing more to watch for", not as an error: this is a best-effort
// mitigation for one specific known bug, never a new way for Run itself
// to fail. The connection is torn down (via ctx) the moment exited
// closes, so this watcher is never itself one more open connection
// keeping k6's own shutdown wait above zero.
func waitForDashboardStopEvent(dashboardURL string, exited <-chan struct{}) bool {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	go func() {
		select {
		case <-exited:
		case <-ctx.Done():
		}
		cancel()
	}()

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, strings.TrimSpace(dashboardURL)+"/events", nil)
	if err != nil {
		return false
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return false
	}
	defer resp.Body.Close()

	scanner := bufio.NewScanner(resp.Body)
	for scanner.Scan() {
		if strings.HasPrefix(scanner.Text(), "event: stop") {
			return true
		}
	}
	return false
}

// k6BinEnv, when set, overrides which k6 binary Run shells out to — the
// path to a custom binary built by scripts/build-k6.sh (bundling
// k6/x/promscrape, see docs/plans/xk6-live-dashboard.md), instead of
// whatever "k6" resolves to on PATH. Unset by default so existing installs
// (stock k6 on PATH) keep working unchanged; this becomes the default once
// the live-dashboard integration actually needs the extension at runtime.
const k6BinEnv = "MYRTILLE_K6_BIN"

// HasCustomBinary reports whether MYRTILLE_K6_BIN is set — i.e. whether a
// custom k6 binary bundling k6/x/promscrape will be used. internal/k6gen
// calls this before deciding whether to wire promscrape into a generated
// script: stock k6 doesn't have that extension, so injecting the import
// based on service.metrics.url alone (regardless of which binary will
// actually run the script) breaks any run that hasn't opted into
// MYRTILLE_K6_BIN — found by running examples/demo-service's own config
// (which sets service.metrics.url for the still-separate Go-side scraper)
// against stock k6: it failed trying to resolve k6/x/promscrape. Doesn't
// validate the path (unlike resolveK6Binary) — that's Run's job when it
// actually shells out; this only needs to answer "is the intent there".
func HasCustomBinary() bool {
	v, ok := os.LookupEnv(k6BinEnv)
	return ok && v != ""
}

// resolveK6Binary returns the path to the k6 executable Run should invoke:
// $MYRTILLE_K6_BIN if set (validated to exist), otherwise "k6" resolved
// from PATH as before — checked in that order. A release tarball extracts
// myrtille and its bundled k6 side by side (see
// docs/plans/single-binary-distribution.md), so the middle branch is what
// makes the live dashboard work out of the box for anyone using an official
// release, with no configuration at all. custom reports whether either of
// the first two branches matched — Run uses it to decide whether a live
// web-dashboard can be requested at all (only a binary bundling
// k6/x/promscrape supports it).
func resolveK6Binary() (path string, custom bool, err error) {
	if v, ok := os.LookupEnv(k6BinEnv); ok && v != "" {
		if _, err := os.Stat(v); err != nil {
			return "", false, fmt.Errorf("%s=%s: %w", k6BinEnv, v, err)
		}
		return v, true, nil
	}

	if v, ok := coLocatedK6Binary(); ok {
		return v, true, nil
	}

	path, err = exec.LookPath("k6")
	if err != nil {
		return "", false, fmt.Errorf("k6 binary not found on PATH: %w", err)
	}
	return path, false, nil
}

// coLocatedK6Binary looks for a "k6" file next to the currently running
// myrtille executable. Unlike MYRTILLE_K6_BIN (an explicit ask, so a
// mistake there should fail loudly), this is an implicit convenience: any
// failure along the way just means "no match, fall through to PATH" —
// never an error.
func coLocatedK6Binary() (string, bool) {
	self, err := os.Executable()
	if err != nil {
		return "", false
	}
	return coLocatedK6BinaryFor(self)
}

// coLocatedK6BinaryFor is coLocatedK6Binary's logic with the "self" path
// injected, so it's testable without depending on the test binary's own
// os.Executable() location.
func coLocatedK6BinaryFor(self string) (string, bool) {
	// os.Executable's result may itself be a symlink (e.g. myrtille
	// installed at /usr/local/bin/myrtille pointing elsewhere) — resolve it
	// so the directory searched is where the real binary (and whatever's
	// bundled alongside it) actually lives, not the symlink's own directory.
	resolved, err := filepath.EvalSymlinks(self)
	if err != nil {
		return "", false
	}

	candidate := filepath.Join(filepath.Dir(resolved), "k6")
	info, err := os.Stat(candidate)
	if err != nil || info.IsDir() {
		return "", false
	}

	return candidate, true
}

func summaryFilePath() string {
	return fmt.Sprintf("%s/myrtille-k6-summary-%d.json", os.TempDir(), time.Now().UnixNano())
}

func dashboardConfigPath() string {
	return fmt.Sprintf("%s/myrtille-k6-dashboard-config-%d.json", os.TempDir(), time.Now().UnixNano())
}

func dashboardExportPath() string {
	return fmt.Sprintf("%s/myrtille-k6-dashboard-export-%d.html", os.TempDir(), time.Now().UnixNano())
}

// buildEnv returns the child process environment: the current process's
// environment with custom entries applied on top, deduplicating by key
// (repeating a key in a Cmd.Env slice has unspecified precedence, so we
// resolve it ourselves).
func buildEnv(custom map[string]string) []string {
	env := make(map[string]string)
	for _, kv := range os.Environ() {
		if i := strings.IndexByte(kv, '='); i >= 0 {
			env[kv[:i]] = kv[i+1:]
		}
	}
	for k, v := range custom {
		env[k] = v
	}

	out := make([]string, 0, len(env))
	for k, v := range env {
		out = append(out, k+"="+v)
	}
	return out
}

// rawCheck/rawGroup mirror the shape of a group under root_group in k6's
// --summary-export JSON: each group has its own checks (keyed by check name)
// plus nested sub-groups, recursively, so a scenario using group() reports
// checks at whatever depth they were declared at.
type rawCheck struct {
	Name   string `json:"name"`
	Path   string `json:"path"`
	Passes int    `json:"passes"`
	Fails  int    `json:"fails"`
}

type rawGroup struct {
	Checks map[string]rawCheck `json:"checks"`
	Groups map[string]rawGroup `json:"groups"`
}

// flattenChecks walks a group's checks and its nested groups' checks into a
// single slice, in no particular order (the caller sorts by Path).
func flattenChecks(g rawGroup) []CheckResult {
	checks := make([]CheckResult, 0, len(g.Checks))
	for _, c := range g.Checks {
		checks = append(checks, CheckResult{Name: c.Name, Path: c.Path, Passes: c.Passes, Fails: c.Fails})
	}
	for _, sub := range g.Groups {
		checks = append(checks, flattenChecks(sub)...)
	}
	return checks
}

// parseSummary decodes a k6 --summary-export JSON payload. Each metric's
// fields are split between numeric stats (kept in Values) and its
// "thresholds" object (kept in Thresholds), tolerating unknown/extra
// fields since k6's summary schema isn't stable across versions. Named
// checks are read from root_group, which k6 always populates regardless of
// whether the script defines its own handleSummary().
func parseSummary(data []byte) (*Summary, error) {
	var raw struct {
		Metrics   map[string]map[string]any `json:"metrics"`
		RootGroup rawGroup                  `json:"root_group"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("parsing k6 summary: %w", err)
	}

	summary := &Summary{Metrics: make(map[string]MetricSummary, len(raw.Metrics))}
	for name, fields := range raw.Metrics {
		ms := MetricSummary{Values: map[string]float64{}, Thresholds: map[string]bool{}}
		for key, val := range fields {
			if key == "thresholds" {
				thresholds, ok := val.(map[string]any)
				if !ok {
					continue
				}
				for expr, tv := range thresholds {
					// Real k6 (confirmed against both stock and a custom
					// xk6 build) emits a flat bool per threshold
					// expression, not {"ok": bool} - accept both since the
					// summary schema isn't stable across versions (see this
					// func's doc comment). The flat form is INVERTED: k6's
					// own --summary-export code
					// (internal/js/summary-wrapper.js's oldJSONSummary) sets
					// it to `!threshold.ok`, so true means the threshold was
					// crossed (failed) - confirmed against three real runs
					// (one deliberately failing, one deliberately passing)
					// before trusting it. The {"ok": bool} shape, if it's
					// ever actually emitted, is self-describing and taken
					// literally.
					switch v := tv.(type) {
					case bool:
						ms.Thresholds[expr] = !v
					case map[string]any:
						if ok2, ok := v["ok"].(bool); ok {
							ms.Thresholds[expr] = ok2
						}
					}
				}
				continue
			}
			if fv, ok := val.(float64); ok {
				ms.Values[key] = fv
			}
		}
		summary.Metrics[name] = ms
	}

	summary.Checks = flattenChecks(raw.RootGroup)
	sort.Slice(summary.Checks, func(i, j int) bool { return summary.Checks[i].Path < summary.Checks[j].Path })

	return summary, nil
}
