version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net.Conn).Close
        - os.Remove
        - os.RemoveAll
        - os.Unsetenv
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
